title: blog@anartri
description: "buralar bir zamanlar bağ bahçeydi"
author:
  name: "levent"
  email: "levent@anartri.net"
  url: "https://anartri.net"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "levent"
year : "2021"
